/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlumniRequestDTO model module.
 * @module model/AlumniRequestDTO
 * @version 1.0.0
 */
class AlumniRequestDTO {
    /**
     * Constructs a new <code>AlumniRequestDTO</code>.
     * @alias module:model/AlumniRequestDTO
     * @param nom {String} Nom de famille
     * @param prenom {String} Prénom
     * @param email {String} Adresse email
     * @param motDePasse {String} Mot de passe
     * @param telephone {String} Numéro de téléphone (format Sénégal)
     */
    constructor(nom, prenom, email, motDePasse, telephone) { 
        
        AlumniRequestDTO.initialize(this, nom, prenom, email, motDePasse, telephone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nom, prenom, email, motDePasse, telephone) { 
        obj['nom'] = nom;
        obj['prenom'] = prenom;
        obj['email'] = email;
        obj['motDePasse'] = motDePasse;
        obj['telephone'] = telephone;
    }

    /**
     * Constructs a <code>AlumniRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlumniRequestDTO} obj Optional instance to populate.
     * @return {module:model/AlumniRequestDTO} The populated <code>AlumniRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlumniRequestDTO();

            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('motDePasse')) {
                obj['motDePasse'] = ApiClient.convertToType(data['motDePasse'], 'String');
            }
            if (data.hasOwnProperty('telephone')) {
                obj['telephone'] = ApiClient.convertToType(data['telephone'], 'String');
            }
            if (data.hasOwnProperty('profession')) {
                obj['profession'] = ApiClient.convertToType(data['profession'], 'String');
            }
            if (data.hasOwnProperty('entreprise')) {
                obj['entreprise'] = ApiClient.convertToType(data['entreprise'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlumniRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlumniRequestDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AlumniRequestDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nom'] && !(typeof data['nom'] === 'string' || data['nom'] instanceof String)) {
            throw new Error("Expected the field `nom` to be a primitive type in the JSON string but got " + data['nom']);
        }
        // ensure the json data is a string
        if (data['prenom'] && !(typeof data['prenom'] === 'string' || data['prenom'] instanceof String)) {
            throw new Error("Expected the field `prenom` to be a primitive type in the JSON string but got " + data['prenom']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['motDePasse'] && !(typeof data['motDePasse'] === 'string' || data['motDePasse'] instanceof String)) {
            throw new Error("Expected the field `motDePasse` to be a primitive type in the JSON string but got " + data['motDePasse']);
        }
        // ensure the json data is a string
        if (data['telephone'] && !(typeof data['telephone'] === 'string' || data['telephone'] instanceof String)) {
            throw new Error("Expected the field `telephone` to be a primitive type in the JSON string but got " + data['telephone']);
        }
        // ensure the json data is a string
        if (data['profession'] && !(typeof data['profession'] === 'string' || data['profession'] instanceof String)) {
            throw new Error("Expected the field `profession` to be a primitive type in the JSON string but got " + data['profession']);
        }
        // ensure the json data is a string
        if (data['entreprise'] && !(typeof data['entreprise'] === 'string' || data['entreprise'] instanceof String)) {
            throw new Error("Expected the field `entreprise` to be a primitive type in the JSON string but got " + data['entreprise']);
        }

        return true;
    }


}

AlumniRequestDTO.RequiredProperties = ["nom", "prenom", "email", "motDePasse", "telephone"];

/**
 * Nom de famille
 * @member {String} nom
 */
AlumniRequestDTO.prototype['nom'] = undefined;

/**
 * Prénom
 * @member {String} prenom
 */
AlumniRequestDTO.prototype['prenom'] = undefined;

/**
 * Adresse email
 * @member {String} email
 */
AlumniRequestDTO.prototype['email'] = undefined;

/**
 * Nom d'utilisateur (optionnel)
 * @member {String} username
 */
AlumniRequestDTO.prototype['username'] = undefined;

/**
 * Mot de passe
 * @member {String} motDePasse
 */
AlumniRequestDTO.prototype['motDePasse'] = undefined;

/**
 * Numéro de téléphone (format Sénégal)
 * @member {String} telephone
 */
AlumniRequestDTO.prototype['telephone'] = undefined;

/**
 * Profession actuelle
 * @member {String} profession
 */
AlumniRequestDTO.prototype['profession'] = undefined;

/**
 * Entreprise actuelle
 * @member {String} entreprise
 */
AlumniRequestDTO.prototype['entreprise'] = undefined;






export default AlumniRequestDTO;

