/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CodeValidationCheckDTO model module.
 * @module model/CodeValidationCheckDTO
 * @version 1.0.0
 */
class CodeValidationCheckDTO {
    /**
     * Constructs a new <code>CodeValidationCheckDTO</code>.
     * @alias module:model/CodeValidationCheckDTO
     * @param email {String} Email de l'utilisateur
     * @param code {String} Code de validation reçu par email
     */
    constructor(email, code) { 
        
        CodeValidationCheckDTO.initialize(this, email, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, code) { 
        obj['email'] = email;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>CodeValidationCheckDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CodeValidationCheckDTO} obj Optional instance to populate.
     * @return {module:model/CodeValidationCheckDTO} The populated <code>CodeValidationCheckDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CodeValidationCheckDTO();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CodeValidationCheckDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CodeValidationCheckDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CodeValidationCheckDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}

CodeValidationCheckDTO.RequiredProperties = ["email", "code"];

/**
 * Email de l'utilisateur
 * @member {String} email
 */
CodeValidationCheckDTO.prototype['email'] = undefined;

/**
 * Code de validation reçu par email
 * @member {String} code
 */
CodeValidationCheckDTO.prototype['code'] = undefined;






export default CodeValidationCheckDTO;

