/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CodeValidationRequestDTO model module.
 * @module model/CodeValidationRequestDTO
 * @version 1.0.0
 */
class CodeValidationRequestDTO {
    /**
     * Constructs a new <code>CodeValidationRequestDTO</code>.
     * @alias module:model/CodeValidationRequestDTO
     * @param email {String} Email de l'utilisateur
     */
    constructor(email) { 
        
        CodeValidationRequestDTO.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>CodeValidationRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CodeValidationRequestDTO} obj Optional instance to populate.
     * @return {module:model/CodeValidationRequestDTO} The populated <code>CodeValidationRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CodeValidationRequestDTO();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CodeValidationRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CodeValidationRequestDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CodeValidationRequestDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

CodeValidationRequestDTO.RequiredProperties = ["email"];

/**
 * Email de l'utilisateur
 * @member {String} email
 */
CodeValidationRequestDTO.prototype['email'] = undefined;






export default CodeValidationRequestDTO;

