/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EtudiantRequestDTO model module.
 * @module model/EtudiantRequestDTO
 * @version 1.0.0
 */
class EtudiantRequestDTO {
    /**
     * Constructs a new <code>EtudiantRequestDTO</code>.
     * @alias module:model/EtudiantRequestDTO
     * @param nom {String} Nom de famille
     * @param prenom {String} Prénom
     * @param email {String} Adresse email
     * @param motDePasse {String} Mot de passe
     * @param numeroCarteEtudiant {String} Numéro de carte étudiant
     * @param niveau {String} Niveau d'études
     * @param filiere {String} Filière d'études
     */
    constructor(nom, prenom, email, motDePasse, numeroCarteEtudiant, niveau, filiere) { 
        
        EtudiantRequestDTO.initialize(this, nom, prenom, email, motDePasse, numeroCarteEtudiant, niveau, filiere);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nom, prenom, email, motDePasse, numeroCarteEtudiant, niveau, filiere) { 
        obj['nom'] = nom;
        obj['prenom'] = prenom;
        obj['email'] = email;
        obj['motDePasse'] = motDePasse;
        obj['numeroCarteEtudiant'] = numeroCarteEtudiant;
        obj['niveau'] = niveau;
        obj['filiere'] = filiere;
    }

    /**
     * Constructs a <code>EtudiantRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EtudiantRequestDTO} obj Optional instance to populate.
     * @return {module:model/EtudiantRequestDTO} The populated <code>EtudiantRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EtudiantRequestDTO();

            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('motDePasse')) {
                obj['motDePasse'] = ApiClient.convertToType(data['motDePasse'], 'String');
            }
            if (data.hasOwnProperty('telephone')) {
                obj['telephone'] = ApiClient.convertToType(data['telephone'], 'String');
            }
            if (data.hasOwnProperty('numeroCarteEtudiant')) {
                obj['numeroCarteEtudiant'] = ApiClient.convertToType(data['numeroCarteEtudiant'], 'String');
            }
            if (data.hasOwnProperty('niveau')) {
                obj['niveau'] = ApiClient.convertToType(data['niveau'], 'String');
            }
            if (data.hasOwnProperty('filiere')) {
                obj['filiere'] = ApiClient.convertToType(data['filiere'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EtudiantRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EtudiantRequestDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EtudiantRequestDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nom'] && !(typeof data['nom'] === 'string' || data['nom'] instanceof String)) {
            throw new Error("Expected the field `nom` to be a primitive type in the JSON string but got " + data['nom']);
        }
        // ensure the json data is a string
        if (data['prenom'] && !(typeof data['prenom'] === 'string' || data['prenom'] instanceof String)) {
            throw new Error("Expected the field `prenom` to be a primitive type in the JSON string but got " + data['prenom']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['motDePasse'] && !(typeof data['motDePasse'] === 'string' || data['motDePasse'] instanceof String)) {
            throw new Error("Expected the field `motDePasse` to be a primitive type in the JSON string but got " + data['motDePasse']);
        }
        // ensure the json data is a string
        if (data['telephone'] && !(typeof data['telephone'] === 'string' || data['telephone'] instanceof String)) {
            throw new Error("Expected the field `telephone` to be a primitive type in the JSON string but got " + data['telephone']);
        }
        // ensure the json data is a string
        if (data['numeroCarteEtudiant'] && !(typeof data['numeroCarteEtudiant'] === 'string' || data['numeroCarteEtudiant'] instanceof String)) {
            throw new Error("Expected the field `numeroCarteEtudiant` to be a primitive type in the JSON string but got " + data['numeroCarteEtudiant']);
        }
        // ensure the json data is a string
        if (data['niveau'] && !(typeof data['niveau'] === 'string' || data['niveau'] instanceof String)) {
            throw new Error("Expected the field `niveau` to be a primitive type in the JSON string but got " + data['niveau']);
        }
        // ensure the json data is a string
        if (data['filiere'] && !(typeof data['filiere'] === 'string' || data['filiere'] instanceof String)) {
            throw new Error("Expected the field `filiere` to be a primitive type in the JSON string but got " + data['filiere']);
        }

        return true;
    }


}

EtudiantRequestDTO.RequiredProperties = ["nom", "prenom", "email", "motDePasse", "numeroCarteEtudiant", "niveau", "filiere"];

/**
 * Nom de famille
 * @member {String} nom
 */
EtudiantRequestDTO.prototype['nom'] = undefined;

/**
 * Prénom
 * @member {String} prenom
 */
EtudiantRequestDTO.prototype['prenom'] = undefined;

/**
 * Adresse email
 * @member {String} email
 */
EtudiantRequestDTO.prototype['email'] = undefined;

/**
 * Nom d'utilisateur (optionnel)
 * @member {String} username
 */
EtudiantRequestDTO.prototype['username'] = undefined;

/**
 * Mot de passe
 * @member {String} motDePasse
 */
EtudiantRequestDTO.prototype['motDePasse'] = undefined;

/**
 * Numéro de téléphone (format Sénégal)
 * @member {String} telephone
 */
EtudiantRequestDTO.prototype['telephone'] = undefined;

/**
 * Numéro de carte étudiant
 * @member {String} numeroCarteEtudiant
 */
EtudiantRequestDTO.prototype['numeroCarteEtudiant'] = undefined;

/**
 * Niveau d'études
 * @member {String} niveau
 */
EtudiantRequestDTO.prototype['niveau'] = undefined;

/**
 * Filière d'études
 * @member {String} filiere
 */
EtudiantRequestDTO.prototype['filiere'] = undefined;






export default EtudiantRequestDTO;

