/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UtilisateurResponseDTO from './UtilisateurResponseDTO';

/**
 * The GetAllUtilisateursFiltered200Response model module.
 * @module model/GetAllUtilisateursFiltered200Response
 * @version 1.0.0
 */
class GetAllUtilisateursFiltered200Response {
    /**
     * Constructs a new <code>GetAllUtilisateursFiltered200Response</code>.
     * @alias module:model/GetAllUtilisateursFiltered200Response
     */
    constructor() { 
        
        GetAllUtilisateursFiltered200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAllUtilisateursFiltered200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAllUtilisateursFiltered200Response} obj Optional instance to populate.
     * @return {module:model/GetAllUtilisateursFiltered200Response} The populated <code>GetAllUtilisateursFiltered200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAllUtilisateursFiltered200Response();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [UtilisateurResponseDTO]);
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAllUtilisateursFiltered200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAllUtilisateursFiltered200Response</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                UtilisateurResponseDTO.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/UtilisateurResponseDTO>} content
 */
GetAllUtilisateursFiltered200Response.prototype['content'] = undefined;

/**
 * @member {Number} totalElements
 */
GetAllUtilisateursFiltered200Response.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
GetAllUtilisateursFiltered200Response.prototype['totalPages'] = undefined;

/**
 * @member {Number} size
 */
GetAllUtilisateursFiltered200Response.prototype['size'] = undefined;

/**
 * @member {Number} number
 */
GetAllUtilisateursFiltered200Response.prototype['number'] = undefined;






export default GetAllUtilisateursFiltered200Response;

