/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginRequest model module.
 * @module model/LoginRequest
 * @version 1.0.0
 */
class LoginRequest {
    /**
     * Constructs a new <code>LoginRequest</code>.
     * @alias module:model/LoginRequest
     * @param email {String} Email de l'utilisateur
     * @param motDePasse {String} Mot de passe de l'utilisateur
     */
    constructor(email, motDePasse) { 
        
        LoginRequest.initialize(this, email, motDePasse);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, motDePasse) { 
        obj['email'] = email;
        obj['motDePasse'] = motDePasse;
    }

    /**
     * Constructs a <code>LoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginRequest} obj Optional instance to populate.
     * @return {module:model/LoginRequest} The populated <code>LoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('motDePasse')) {
                obj['motDePasse'] = ApiClient.convertToType(data['motDePasse'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoginRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['motDePasse'] && !(typeof data['motDePasse'] === 'string' || data['motDePasse'] instanceof String)) {
            throw new Error("Expected the field `motDePasse` to be a primitive type in the JSON string but got " + data['motDePasse']);
        }

        return true;
    }


}

LoginRequest.RequiredProperties = ["email", "motDePasse"];

/**
 * Email de l'utilisateur
 * @member {String} email
 */
LoginRequest.prototype['email'] = undefined;

/**
 * Mot de passe de l'utilisateur
 * @member {String} motDePasse
 */
LoginRequest.prototype['motDePasse'] = undefined;






export default LoginRequest;

