/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleResponseDTO model module.
 * @module model/RoleResponseDTO
 * @version 1.0.0
 */
class RoleResponseDTO {
    /**
     * Constructs a new <code>RoleResponseDTO</code>.
     * @alias module:model/RoleResponseDTO
     */
    constructor() { 
        
        RoleResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RoleResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleResponseDTO} obj Optional instance to populate.
     * @return {module:model/RoleResponseDTO} The populated <code>RoleResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleResponseDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('libelle')) {
                obj['libelle'] = ApiClient.convertToType(data['libelle'], 'String');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RoleResponseDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RoleResponseDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['libelle'] && !(typeof data['libelle'] === 'string' || data['libelle'] instanceof String)) {
            throw new Error("Expected the field `libelle` to be a primitive type in the JSON string but got " + data['libelle']);
        }

        return true;
    }


}



/**
 * Identifiant unique du rôle
 * @member {Number} id
 */
RoleResponseDTO.prototype['id'] = undefined;

/**
 * Libellé du rôle
 * @member {String} libelle
 */
RoleResponseDTO.prototype['libelle'] = undefined;

/**
 * Indique si le rôle est supprimé
 * @member {Boolean} deleted
 */
RoleResponseDTO.prototype['deleted'] = undefined;






export default RoleResponseDTO;

