/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleRequestDTO model module.
 * @module model/RoleRequestDTO
 * @version 1.0.0
 */
class RoleRequestDTO {
    /**
     * Constructs a new <code>RoleRequestDTO</code>.
     * @alias module:model/RoleRequestDTO
     * @param libelle {String} Libellé du rôle (majuscules et underscores uniquement)
     */
    constructor(libelle) { 
        
        RoleRequestDTO.initialize(this, libelle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, libelle) { 
        obj['libelle'] = libelle;
    }

    /**
     * Constructs a <code>RoleRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleRequestDTO} obj Optional instance to populate.
     * @return {module:model/RoleRequestDTO} The populated <code>RoleRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleRequestDTO();

            if (data.hasOwnProperty('libelle')) {
                obj['libelle'] = ApiClient.convertToType(data['libelle'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RoleRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RoleRequestDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RoleRequestDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['libelle'] && !(typeof data['libelle'] === 'string' || data['libelle'] instanceof String)) {
            throw new Error("Expected the field `libelle` to be a primitive type in the JSON string but got " + data['libelle']);
        }

        return true;
    }


}

RoleRequestDTO.RequiredProperties = ["libelle"];

/**
 * Libellé du rôle (majuscules et underscores uniquement)
 * @member {String} libelle
 */
RoleRequestDTO.prototype['libelle'] = undefined;






export default RoleRequestDTO;

