/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UtilisateurRequestDTO model module.
 * @module model/UtilisateurRequestDTO
 * @version 1.0.0
 */
class UtilisateurRequestDTO {
    /**
     * Constructs a new <code>UtilisateurRequestDTO</code>.
     * @alias module:model/UtilisateurRequestDTO
     * @param nom {String} Nom de famille
     * @param prenom {String} Prénom
     * @param email {String} Adresse email
     * @param username {String} Nom d'utilisateur
     * @param motDePasse {String} Mot de passe
     * @param telephone {String} Numéro de téléphone (format Sénégal)
     * @param role {String} Rôle de l'utilisateur
     */
    constructor(nom, prenom, email, username, motDePasse, telephone, role) { 
        
        UtilisateurRequestDTO.initialize(this, nom, prenom, email, username, motDePasse, telephone, role);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nom, prenom, email, username, motDePasse, telephone, role) { 
        obj['nom'] = nom;
        obj['prenom'] = prenom;
        obj['email'] = email;
        obj['username'] = username;
        obj['motDePasse'] = motDePasse;
        obj['telephone'] = telephone;
        obj['role'] = role;
    }

    /**
     * Constructs a <code>UtilisateurRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UtilisateurRequestDTO} obj Optional instance to populate.
     * @return {module:model/UtilisateurRequestDTO} The populated <code>UtilisateurRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UtilisateurRequestDTO();

            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('motDePasse')) {
                obj['motDePasse'] = ApiClient.convertToType(data['motDePasse'], 'String');
            }
            if (data.hasOwnProperty('telephone')) {
                obj['telephone'] = ApiClient.convertToType(data['telephone'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UtilisateurRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UtilisateurRequestDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UtilisateurRequestDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nom'] && !(typeof data['nom'] === 'string' || data['nom'] instanceof String)) {
            throw new Error("Expected the field `nom` to be a primitive type in the JSON string but got " + data['nom']);
        }
        // ensure the json data is a string
        if (data['prenom'] && !(typeof data['prenom'] === 'string' || data['prenom'] instanceof String)) {
            throw new Error("Expected the field `prenom` to be a primitive type in the JSON string but got " + data['prenom']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['motDePasse'] && !(typeof data['motDePasse'] === 'string' || data['motDePasse'] instanceof String)) {
            throw new Error("Expected the field `motDePasse` to be a primitive type in the JSON string but got " + data['motDePasse']);
        }
        // ensure the json data is a string
        if (data['telephone'] && !(typeof data['telephone'] === 'string' || data['telephone'] instanceof String)) {
            throw new Error("Expected the field `telephone` to be a primitive type in the JSON string but got " + data['telephone']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }

        return true;
    }


}

UtilisateurRequestDTO.RequiredProperties = ["nom", "prenom", "email", "username", "motDePasse", "telephone", "role"];

/**
 * Nom de famille
 * @member {String} nom
 */
UtilisateurRequestDTO.prototype['nom'] = undefined;

/**
 * Prénom
 * @member {String} prenom
 */
UtilisateurRequestDTO.prototype['prenom'] = undefined;

/**
 * Adresse email
 * @member {String} email
 */
UtilisateurRequestDTO.prototype['email'] = undefined;

/**
 * Nom d'utilisateur
 * @member {String} username
 */
UtilisateurRequestDTO.prototype['username'] = undefined;

/**
 * Mot de passe
 * @member {String} motDePasse
 */
UtilisateurRequestDTO.prototype['motDePasse'] = undefined;

/**
 * Numéro de téléphone (format Sénégal)
 * @member {String} telephone
 */
UtilisateurRequestDTO.prototype['telephone'] = undefined;

/**
 * Rôle de l'utilisateur
 * @member {String} role
 */
UtilisateurRequestDTO.prototype['role'] = undefined;






export default UtilisateurRequestDTO;

