/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UtilisateurResponseDTO model module.
 * @module model/UtilisateurResponseDTO
 * @version 1.0.0
 */
class UtilisateurResponseDTO {
    /**
     * Constructs a new <code>UtilisateurResponseDTO</code>.
     * @alias module:model/UtilisateurResponseDTO
     */
    constructor() { 
        
        UtilisateurResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UtilisateurResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UtilisateurResponseDTO} obj Optional instance to populate.
     * @return {module:model/UtilisateurResponseDTO} The populated <code>UtilisateurResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UtilisateurResponseDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('telephone')) {
                obj['telephone'] = ApiClient.convertToType(data['telephone'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('actif')) {
                obj['actif'] = ApiClient.convertToType(data['actif'], 'Boolean');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UtilisateurResponseDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UtilisateurResponseDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nom'] && !(typeof data['nom'] === 'string' || data['nom'] instanceof String)) {
            throw new Error("Expected the field `nom` to be a primitive type in the JSON string but got " + data['nom']);
        }
        // ensure the json data is a string
        if (data['prenom'] && !(typeof data['prenom'] === 'string' || data['prenom'] instanceof String)) {
            throw new Error("Expected the field `prenom` to be a primitive type in the JSON string but got " + data['prenom']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['telephone'] && !(typeof data['telephone'] === 'string' || data['telephone'] instanceof String)) {
            throw new Error("Expected the field `telephone` to be a primitive type in the JSON string but got " + data['telephone']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }

        return true;
    }


}



/**
 * Identifiant unique
 * @member {Number} id
 */
UtilisateurResponseDTO.prototype['id'] = undefined;

/**
 * @member {String} nom
 */
UtilisateurResponseDTO.prototype['nom'] = undefined;

/**
 * @member {String} prenom
 */
UtilisateurResponseDTO.prototype['prenom'] = undefined;

/**
 * @member {String} email
 */
UtilisateurResponseDTO.prototype['email'] = undefined;

/**
 * @member {String} telephone
 */
UtilisateurResponseDTO.prototype['telephone'] = undefined;

/**
 * @member {String} username
 */
UtilisateurResponseDTO.prototype['username'] = undefined;

/**
 * Indique si le compte est actif
 * @member {Boolean} actif
 */
UtilisateurResponseDTO.prototype['actif'] = undefined;

/**
 * Indique si le compte est supprimé
 * @member {Boolean} deleted
 */
UtilisateurResponseDTO.prototype['deleted'] = undefined;

/**
 * Rôle de l'utilisateur
 * @member {String} role
 */
UtilisateurResponseDTO.prototype['role'] = undefined;






export default UtilisateurResponseDTO;

