/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LoginRequest from '../model/LoginRequest';
import RefreshRequest from '../model/RefreshRequest';
import TokenResponse from '../model/TokenResponse';
import UtilisateurRequestDTO from '../model/UtilisateurRequestDTO';
import UtilisateurResponseDTO from '../model/UtilisateurResponseDTO';

/**
* Authentification service.
* @module api/AuthentificationApi
* @version 1.0.0
*/
export default class AuthentificationApi {

    /**
    * Constructs a new AuthentificationApi. 
    * @alias module:api/AuthentificationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the inscrire operation.
     * @callback module:api/AuthentificationApi~inscrireCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UtilisateurResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Inscrire un nouvel Utilisateur
     * Crée un nouveau compte utilisateur
     * @param {module:model/UtilisateurRequestDTO} utilisateurRequestDTO 
     * @param {module:api/AuthentificationApi~inscrireCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UtilisateurResponseDTO}
     */
    inscrire(utilisateurRequestDTO, callback) {
      let postBody = utilisateurRequestDTO;
      // verify the required parameter 'utilisateurRequestDTO' is set
      if (utilisateurRequestDTO === undefined || utilisateurRequestDTO === null) {
        throw new Error("Missing the required parameter 'utilisateurRequestDTO' when calling inscrire");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UtilisateurResponseDTO;
      return this.apiClient.callApi(
        '/auth/inscrire', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the login operation.
     * @callback module:api/AuthentificationApi~loginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Connexion utilisateur
     * Authentifie un utilisateur et retourne un token JWT
     * @param {module:model/LoginRequest} loginRequest 
     * @param {module:api/AuthentificationApi~loginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponse}
     */
    login(loginRequest, callback) {
      let postBody = loginRequest;
      // verify the required parameter 'loginRequest' is set
      if (loginRequest === undefined || loginRequest === null) {
        throw new Error("Missing the required parameter 'loginRequest' when calling login");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TokenResponse;
      return this.apiClient.callApi(
        '/auth/connecter', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the logout operation.
     * @callback module:api/AuthentificationApi~logoutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Déconnexion utilisateur
     * Déconnecte l'utilisateur et invalide le refresh token
     * @param {module:model/RefreshRequest} refreshRequest 
     * @param {module:api/AuthentificationApi~logoutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    logout(refreshRequest, callback) {
      let postBody = refreshRequest;
      // verify the required parameter 'refreshRequest' is set
      if (refreshRequest === undefined || refreshRequest === null) {
        throw new Error("Missing the required parameter 'refreshRequest' when calling logout");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/auth/deconnecter', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the refresh operation.
     * @callback module:api/AuthentificationApi~refreshCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Rafraîchir le token JWT
     * Permet de renouveler un token JWT expiré en utilisant le refresh token
     * @param {module:model/RefreshRequest} refreshRequest 
     * @param {module:api/AuthentificationApi~refreshCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponse}
     */
    refresh(refreshRequest, callback) {
      let postBody = refreshRequest;
      // verify the required parameter 'refreshRequest' is set
      if (refreshRequest === undefined || refreshRequest === null) {
        throw new Error("Missing the required parameter 'refreshRequest' when calling refresh");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TokenResponse;
      return this.apiClient.callApi(
        '/auth/refresh', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
