/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RoleRequestDTO from '../model/RoleRequestDTO';
import RoleResponseDTO from '../model/RoleResponseDTO';

/**
* Rles service.
* @module api/RlesApi
* @version 1.0.0
*/
export default class RlesApi {

    /**
    * Constructs a new RlesApi. 
    * @alias module:api/RlesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createRole operation.
     * @callback module:api/RlesApi~createRoleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoleResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Créer un nouveau rôle
     * Crée un nouveau rôle dans le système
     * @param {module:model/RoleRequestDTO} roleRequestDTO 
     * @param {module:api/RlesApi~createRoleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoleResponseDTO}
     */
    createRole(roleRequestDTO, callback) {
      let postBody = roleRequestDTO;
      // verify the required parameter 'roleRequestDTO' is set
      if (roleRequestDTO === undefined || roleRequestDTO === null) {
        throw new Error("Missing the required parameter 'roleRequestDTO' when calling createRole");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoleResponseDTO;
      return this.apiClient.callApi(
        '/roles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllRoles operation.
     * @callback module:api/RlesApi~getAllRolesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/RoleResponseDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Récupérer tous les rôles
     * Retourne la liste de tous les rôles disponibles dans le système
     * @param {module:api/RlesApi~getAllRolesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/RoleResponseDTO>}
     */
    getAllRoles(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [RoleResponseDTO];
      return this.apiClient.callApi(
        '/roles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRoleById operation.
     * @callback module:api/RlesApi~getRoleByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoleResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Récupérer un rôle par son ID
     * Retourne les détails d'un rôle spécifique
     * @param {Number} id 
     * @param {module:api/RlesApi~getRoleByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoleResponseDTO}
     */
    getRoleById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRoleById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RoleResponseDTO;
      return this.apiClient.callApi(
        '/roles/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the softDeleteRole operation.
     * @callback module:api/RlesApi~softDeleteRoleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Supprimer logiquement un rôle
     * Effectue une suppression logique (soft delete) d'un rôle
     * @param {Number} id 
     * @param {module:api/RlesApi~softDeleteRoleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    softDeleteRole(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling softDeleteRole");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/roles/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRole operation.
     * @callback module:api/RlesApi~updateRoleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoleResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mettre à jour un rôle existant
     * Met à jour les informations d'un rôle
     * @param {Number} id 
     * @param {module:model/RoleRequestDTO} roleRequestDTO 
     * @param {module:api/RlesApi~updateRoleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoleResponseDTO}
     */
    updateRole(id, roleRequestDTO, callback) {
      let postBody = roleRequestDTO;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateRole");
      }
      // verify the required parameter 'roleRequestDTO' is set
      if (roleRequestDTO === undefined || roleRequestDTO === null) {
        throw new Error("Missing the required parameter 'roleRequestDTO' when calling updateRole");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoleResponseDTO;
      return this.apiClient.callApi(
        '/roles/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
