/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlumniResponseDTO from '../model/AlumniResponseDTO';
import GetAllUtilisateursFiltered200Response from '../model/GetAllUtilisateursFiltered200Response';
import UtilisateurResponseDTO from '../model/UtilisateurResponseDTO';

/**
* Utilisateurs service.
* @module api/UtilisateursApi
* @version 1.0.0
*/
export default class UtilisateursApi {

    /**
    * Constructs a new UtilisateursApi. 
    * @alias module:api/UtilisateursApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the emailExists operation.
     * @callback module:api/UtilisateursApi~emailExistsCallback
     * @param {String} error Error message, if any.
     * @param {Boolean} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Vérifier si un email existe
     * Vérifie si un email est déjà utilisé dans le système
     * @param {String} email 
     * @param {module:api/UtilisateursApi~emailExistsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Boolean}
     */
    emailExists(email, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling emailExists");
      }

      let pathParams = {
        'email': email
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/utilisateurs/exists/email/{email}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllUtilisateursFiltered operation.
     * @callback module:api/UtilisateursApi~getAllUtilisateursFilteredCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllUtilisateursFiltered200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lister et filtrer les utilisateurs
     * Permet de lister les utilisateurs avec pagination, filtre par actif et filtre par suppression (soft delete). 
     * @param {Object} opts Optional parameters
     * @param {Boolean} [actif] Filtre sur l'état d'activation du compte
     * @param {Boolean} [deleted] Filtre sur l'état de suppression logique (soft delete)
     * @param {Number} [page] 
     * @param {Number} [size] 
     * @param {String} [sort] Format: champ,ordre (asc|desc)
     * @param {module:api/UtilisateursApi~getAllUtilisateursFilteredCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllUtilisateursFiltered200Response}
     */
    getAllUtilisateursFiltered(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'actif': opts['actif'],
        'deleted': opts['deleted'],
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllUtilisateursFiltered200Response;
      return this.apiClient.callApi(
        '/utilisateurs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUtilisateurByEmail operation.
     * @callback module:api/UtilisateursApi~getUtilisateurByEmailCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UtilisateurResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Récupérer un utilisateur par email
     * Retourne les informations d'un utilisateur par son email
     * @param {String} email 
     * @param {module:api/UtilisateursApi~getUtilisateurByEmailCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UtilisateurResponseDTO}
     */
    getUtilisateurByEmail(email, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling getUtilisateurByEmail");
      }

      let pathParams = {
        'email': email
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UtilisateurResponseDTO;
      return this.apiClient.callApi(
        '/utilisateurs/email/{email}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchAlumni operation.
     * @callback module:api/UtilisateursApi~searchAlumniCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlumniResponseDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Recherche avancée des alumni
     * Permet de rechercher des alumni à l'aide de filtres optionnels par entreprise et profession. 
     * @param {Object} opts Optional parameters
     * @param {String} [entreprise] Nom de l'entreprise actuelle de l'alumni
     * @param {String} [profession] Profession actuelle de l'alumni (ex: Data Scientist, Médecin...)
     * @param {String} [nom] Le nom de l'Alumni (ex: THIAM, DIOP...) 
     * @param {String} [prenom] Le prenom de l'Alumni (ex: Khoutbou, Ibrahima...) 
     * @param {module:api/UtilisateursApi~searchAlumniCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlumniResponseDTO>}
     */
    searchAlumni(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'entreprise': opts['entreprise'],
        'profession': opts['profession'],
        'nom': opts['nom'],
        'prenom': opts['prenom']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlumniResponseDTO];
      return this.apiClient.callApi(
        '/alumni/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the usernameExists operation.
     * @callback module:api/UtilisateursApi~usernameExistsCallback
     * @param {String} error Error message, if any.
     * @param {Boolean} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Vérifier si un username existe
     * Vérifie si un username est déjà utilisé dans le système
     * @param {String} username 
     * @param {module:api/UtilisateursApi~usernameExistsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Boolean}
     */
    usernameExists(username, callback) {
      let postBody = null;
      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling usernameExists");
      }

      let pathParams = {
        'username': username
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/utilisateurs/exists/username/{username}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
