/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CodeValidationCheckDTO from '../model/CodeValidationCheckDTO';
import CodeValidationRequestDTO from '../model/CodeValidationRequestDTO';

/**
* Validation service.
* @module api/ValidationApi
* @version 1.0.0
*/
export default class ValidationApi {

    /**
    * Constructs a new ValidationApi. 
    * @alias module:api/ValidationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the envoyerCode operation.
     * @callback module:api/ValidationApi~envoyerCodeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Envoyer un code de validation
     * Génère et envoie un code de validation par email
     * @param {module:model/CodeValidationRequestDTO} codeValidationRequestDTO 
     * @param {module:api/ValidationApi~envoyerCodeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    envoyerCode(codeValidationRequestDTO, callback) {
      let postBody = codeValidationRequestDTO;
      // verify the required parameter 'codeValidationRequestDTO' is set
      if (codeValidationRequestDTO === undefined || codeValidationRequestDTO === null) {
        throw new Error("Missing the required parameter 'codeValidationRequestDTO' when calling envoyerCode");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/validation/envoyer', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the verifierCode operation.
     * @callback module:api/ValidationApi~verifierCodeCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Vérifier un code de validation
     * Valide un code fourni par l'utilisateur
     * @param {module:model/CodeValidationCheckDTO} codeValidationCheckDTO 
     * @param {module:api/ValidationApi~verifierCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    verifierCode(codeValidationCheckDTO, callback) {
      let postBody = codeValidationCheckDTO;
      // verify the required parameter 'codeValidationCheckDTO' is set
      if (codeValidationCheckDTO === undefined || codeValidationCheckDTO === null) {
        throw new Error("Missing the required parameter 'codeValidationCheckDTO' when calling verifierCode");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/validation/verifier', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
