/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AlumniRequestDTO from './model/AlumniRequestDTO';
import AlumniResponseDTO from './model/AlumniResponseDTO';
import CodeValidationCheckDTO from './model/CodeValidationCheckDTO';
import CodeValidationRequestDTO from './model/CodeValidationRequestDTO';
import EtudiantRequestDTO from './model/EtudiantRequestDTO';
import EtudiantResponseDTO from './model/EtudiantResponseDTO';
import GetAllUtilisateursFiltered200Response from './model/GetAllUtilisateursFiltered200Response';
import LoginRequest from './model/LoginRequest';
import RefreshRequest from './model/RefreshRequest';
import RoleRequestDTO from './model/RoleRequestDTO';
import RoleResponseDTO from './model/RoleResponseDTO';
import TokenResponse from './model/TokenResponse';
import UtilisateurRequestDTO from './model/UtilisateurRequestDTO';
import UtilisateurResponseDTO from './model/UtilisateurResponseDTO';
import AuthentificationApi from './api/AuthentificationApi';
import RlesApi from './api/RlesApi';
import UtilisateursApi from './api/UtilisateursApi';
import ValidationApi from './api/ValidationApi';


/**
* Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l&#39;authentification. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MsUserApiDeGestionDesUtilisateurs = require('index'); // See note below*.
* var xxxSvc = new MsUserApiDeGestionDesUtilisateurs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MsUserApiDeGestionDesUtilisateurs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MsUserApiDeGestionDesUtilisateurs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MsUserApiDeGestionDesUtilisateurs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AlumniRequestDTO model constructor.
     * @property {module:model/AlumniRequestDTO}
     */
    AlumniRequestDTO,

    /**
     * The AlumniResponseDTO model constructor.
     * @property {module:model/AlumniResponseDTO}
     */
    AlumniResponseDTO,

    /**
     * The CodeValidationCheckDTO model constructor.
     * @property {module:model/CodeValidationCheckDTO}
     */
    CodeValidationCheckDTO,

    /**
     * The CodeValidationRequestDTO model constructor.
     * @property {module:model/CodeValidationRequestDTO}
     */
    CodeValidationRequestDTO,

    /**
     * The EtudiantRequestDTO model constructor.
     * @property {module:model/EtudiantRequestDTO}
     */
    EtudiantRequestDTO,

    /**
     * The EtudiantResponseDTO model constructor.
     * @property {module:model/EtudiantResponseDTO}
     */
    EtudiantResponseDTO,

    /**
     * The GetAllUtilisateursFiltered200Response model constructor.
     * @property {module:model/GetAllUtilisateursFiltered200Response}
     */
    GetAllUtilisateursFiltered200Response,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The RefreshRequest model constructor.
     * @property {module:model/RefreshRequest}
     */
    RefreshRequest,

    /**
     * The RoleRequestDTO model constructor.
     * @property {module:model/RoleRequestDTO}
     */
    RoleRequestDTO,

    /**
     * The RoleResponseDTO model constructor.
     * @property {module:model/RoleResponseDTO}
     */
    RoleResponseDTO,

    /**
     * The TokenResponse model constructor.
     * @property {module:model/TokenResponse}
     */
    TokenResponse,

    /**
     * The UtilisateurRequestDTO model constructor.
     * @property {module:model/UtilisateurRequestDTO}
     */
    UtilisateurRequestDTO,

    /**
     * The UtilisateurResponseDTO model constructor.
     * @property {module:model/UtilisateurResponseDTO}
     */
    UtilisateurResponseDTO,

    /**
    * The AuthentificationApi service constructor.
    * @property {module:api/AuthentificationApi}
    */
    AuthentificationApi,

    /**
    * The RlesApi service constructor.
    * @property {module:api/RlesApi}
    */
    RlesApi,

    /**
    * The UtilisateursApi service constructor.
    * @property {module:api/UtilisateursApi}
    */
    UtilisateursApi,

    /**
    * The ValidationApi service constructor.
    * @property {module:api/ValidationApi}
    */
    ValidationApi
};
