/* tslint:disable */
/* eslint-disable */
/**
 * MS CV V2 API
 * API for Managing CVs and Templates in MS CV V2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CompetenceDTO {
    'nom'?: string;
    'niveau'?: string;
}
export interface CompetenceResponseDTO {
    'nom'?: string;
    'niveau'?: string;
}
export interface CvRequestDTO {
    'templateId': number;
    'titreProfil'?: string;
    'telephone'?: string;
    'email'?: string;
    'nom'?: string;
    'prenom'?: string;
    'adresse'?: string;
    'resumeProfil'?: string;
    'formations'?: Array<FormationDTO>;
    'experiences'?: Array<ExperienceDTO>;
    'competences'?: Array<CompetenceDTO>;
    'langues'?: Array<LangueDTO>;
    'interets'?: Array<InteretDTO>;
}
export interface CvResponseDTO {
    'id'?: number;
    'userId'?: number;
    'prenom'?: string;
    'nom'?: string;
    'templateId'?: number;
    'templateNom'?: string;
    'titreProfil'?: string;
    'telephone'?: string;
    'email'?: string;
    'adresse'?: string;
    'resumeProfil'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'formations'?: Array<FormationResponseDTO>;
    'experiences'?: Array<ExperienceResponseDTO>;
    'competences'?: Array<CompetenceResponseDTO>;
    'langues'?: Array<LangueResponseDTO>;
    'interets'?: Array<InteretResponseDTO>;
}
export interface ExperienceDTO {
    'poste'?: string;
    'entreprise'?: string;
    'ville'?: string;
    'dateDebut'?: string;
    'dateFin'?: string;
    'description'?: string;
}
export interface ExperienceResponseDTO {
    'poste'?: string;
    'entreprise'?: string;
    'ville'?: string;
    'dateDebut'?: string;
    'dateFin'?: string;
    'description'?: string;
}
export interface FormationDTO {
    'diplome'?: string;
    'etablissement'?: string;
    'ville'?: string;
    'anneeDebut'?: string;
    'anneeFin'?: string;
}
export interface FormationResponseDTO {
    'diplome'?: string;
    'etablissement'?: string;
    'ville'?: string;
    'anneeDebut'?: string;
    'anneeFin'?: string;
}
export interface InteretDTO {
    'libelle'?: string;
}
export interface InteretResponseDTO {
    'libelle'?: string;
}
export interface LangueDTO {
    'nom'?: string;
    'niveau'?: string;
}
export interface LangueResponseDTO {
    'nom'?: string;
    'niveau'?: string;
}
export interface SectionRequestDTO {
    'type'?: string;
    'htmlContent'?: string;
    'ordre'?: number;
}
export interface SectionResponseDTO {
    'id'?: number;
    'type'?: string;
    'htmlContent'?: string;
    'ordre'?: number;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface TemplateRequestDTO {
    'nom'?: string;
    'isGlobal'?: boolean;
    'sections'?: Array<SectionRequestDTO>;
}
export interface TemplateResponseDTO {
    'id'?: number;
    'nom'?: string;
    'isGlobal'?: boolean;
    'userId'?: number;
    'sections'?: Array<SectionResponseDTO>;
    'createdAt'?: string;
    'updatedAt'?: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new CV
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCv: async (cvRequestDTO: CvRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cvRequestDTO' is not null or undefined
            assertParamExists('createCv', 'cvRequestDTO', cvRequestDTO)
            const localVarPath = `/cvs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cvRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new template
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTemplate: async (templateRequestDTO: TemplateRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateRequestDTO' is not null or undefined
            assertParamExists('createTemplate', 'templateRequestDTO', templateRequestDTO)
            const localVarPath = `/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(templateRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a CV
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCv: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCv', 'id', id)
            const localVarPath = `/cvs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTemplate', 'id', id)
            const localVarPath = `/templates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download CV as PDF
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCvPdf: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('downloadCvPdf', 'id', id)
            const localVarPath = `/cvs/{id}/pdf`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTemplates: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get CV by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCvById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCvById', 'id', id)
            const localVarPath = `/cvs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get My CVs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCvs: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cvs/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get template by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTemplateById', 'id', id)
            const localVarPath = `/templates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a CV
         * @param {number} id 
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCv: async (id: number, cvRequestDTO: CvRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCv', 'id', id)
            // verify required parameter 'cvRequestDTO' is not null or undefined
            assertParamExists('updateCv', 'cvRequestDTO', cvRequestDTO)
            const localVarPath = `/cvs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cvRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a template
         * @param {number} id 
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTemplate: async (id: number, templateRequestDTO: TemplateRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTemplate', 'id', id)
            // verify required parameter 'templateRequestDTO' is not null or undefined
            assertParamExists('updateTemplate', 'templateRequestDTO', templateRequestDTO)
            const localVarPath = `/templates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(templateRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new CV
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCv(cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CvResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCv(cvRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createCv']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new template
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTemplate(templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTemplate(templateRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a CV
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCv(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCv(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteCv']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTemplate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTemplate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Download CV as PDF
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadCvPdf(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadCvPdf(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.downloadCvPdf']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTemplates(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TemplateResponseDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTemplates(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllTemplates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get CV by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCvById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CvResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCvById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCvById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get My CVs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCvs(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CvResponseDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCvs(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMyCvs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get template by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplateById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplateById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTemplateById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a CV
         * @param {number} id 
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCv(id: number, cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CvResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCv(id, cvRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateCv']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a template
         * @param {number} id 
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTemplate(id: number, templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTemplate(id, templateRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new CV
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCv(cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<CvResponseDTO> {
            return localVarFp.createCv(cvRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new template
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTemplate(templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponseDTO> {
            return localVarFp.createTemplate(templateRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a CV
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCv(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCv(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a template
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTemplate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download CV as PDF
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCvPdf(id: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadCvPdf(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTemplates(options?: RawAxiosRequestConfig): AxiosPromise<Array<TemplateResponseDTO>> {
            return localVarFp.getAllTemplates(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get CV by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCvById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CvResponseDTO> {
            return localVarFp.getCvById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get My CVs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCvs(options?: RawAxiosRequestConfig): AxiosPromise<Array<CvResponseDTO>> {
            return localVarFp.getMyCvs(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get template by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponseDTO> {
            return localVarFp.getTemplateById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a CV
         * @param {number} id 
         * @param {CvRequestDTO} cvRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCv(id: number, cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<CvResponseDTO> {
            return localVarFp.updateCv(id, cvRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a template
         * @param {number} id 
         * @param {TemplateRequestDTO} templateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTemplate(id: number, templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponseDTO> {
            return localVarFp.updateTemplate(id, templateRequestDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new CV
     * @param {CvRequestDTO} cvRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCv(cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createCv(cvRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new template
     * @param {TemplateRequestDTO} templateRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTemplate(templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createTemplate(templateRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a CV
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCv(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteCv(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a template
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTemplate(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTemplate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download CV as PDF
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public downloadCvPdf(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).downloadCvPdf(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllTemplates(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllTemplates(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get CV by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCvById(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCvById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get My CVs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyCvs(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMyCvs(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get template by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplateById(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTemplateById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a CV
     * @param {number} id 
     * @param {CvRequestDTO} cvRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCv(id: number, cvRequestDTO: CvRequestDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateCv(id, cvRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a template
     * @param {number} id 
     * @param {TemplateRequestDTO} templateRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTemplate(id: number, templateRequestDTO: TemplateRequestDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateTemplate(id, templateRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



