/* tslint:disable */
/* eslint-disable */
/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l\'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AlumniProfilRequestDTO {
    'profession'?: string;
    'entreprise'?: string;
}
export interface AlumniRequestDTO {
    /**
     * Nom de famille
     */
    'nom': string;
    /**
     * Prénom
     */
    'prenom': string;
    /**
     * Adresse email
     */
    'email': string;
    /**
     * Nom d\'utilisateur (optionnel)
     */
    'username'?: string;
    /**
     * Mot de passe
     */
    'motDePasse': string;
    /**
     * Numéro de téléphone (format Sénégal)
     */
    'telephone': string;
    /**
     * Profession actuelle
     */
    'profession'?: string;
    /**
     * Entreprise actuelle
     */
    'entreprise'?: string;
}
export interface AlumniResponseDTO {
    /**
     * Identifiant unique
     */
    'id'?: number;
    'nom'?: string;
    'prenom'?: string;
    'email'?: string;
    'username'?: string;
    'telephone'?: string;
    'profession'?: string;
    'entreprise'?: string;
    /**
     * Indique si le compte est actif
     */
    'actif'?: boolean;
    /**
     * Rôle de l\'utilisateur
     */
    'role'?: string;
    /**
     * Indique si le compte est supprimé
     */
    'deleted'?: boolean;
}
export interface CodeValidationCheckDTO {
    /**
     * Email de l\'utilisateur
     */
    'email': string;
    /**
     * Code de validation reçu par email
     */
    'code': string;
}
export interface CodeValidationRequestDTO {
    /**
     * Email de l\'utilisateur
     */
    'email': string;
}
export interface EtudiantProfilRequestDTO {
    /**
     * Numéro de carte étudiant (8 à 10 chiffres)
     */
    'numeroEtudiant': string;
    /**
     * Filière d\'études
     */
    'filiere': string;
    /**
     * Niveau d\'études
     */
    'niveau': string;
}
export interface EtudiantRequestDTO {
    /**
     * Nom de famille
     */
    'nom': string;
    /**
     * Prénom
     */
    'prenom': string;
    /**
     * Adresse email
     */
    'email': string;
    /**
     * Nom d\'utilisateur (optionnel)
     */
    'username'?: string;
    /**
     * Mot de passe
     */
    'motDePasse': string;
    /**
     * Numéro de téléphone (format Sénégal)
     */
    'telephone'?: string;
    /**
     * Numéro de carte étudiant (8 à 10 chiffres)
     */
    'numeroCarteEtudiant': string;
    /**
     * Niveau d\'études
     */
    'niveau': string;
    /**
     * Filière d\'études
     */
    'filiere': string;
}
export interface EtudiantResponseDTO {
    /**
     * Identifiant unique
     */
    'id'?: number;
    'nom'?: string;
    'prenom'?: string;
    'email'?: string;
    'username'?: string;
    'telephone'?: string;
    'numeroCarteEtudiant'?: string;
    'niveau'?: string;
    'filiere'?: string;
    /**
     * Indique si le compte est actif
     */
    'actif'?: boolean;
    /**
     * Rôle de l\'utilisateur
     */
    'role'?: string;
    /**
     * Indique si le compte est supprimé
     */
    'deleted'?: boolean;
}
export interface GetAllUtilisateursFiltered200Response {
    'content'?: Array<UtilisateurResponseDTO>;
    'totalElements'?: number;
    'totalPages'?: number;
    'size'?: number;
    'number'?: number;
}
export interface LoginRequest {
    /**
     * Email de l\'utilisateur
     */
    'email': string;
    /**
     * Mot de passe de l\'utilisateur
     */
    'motDePasse': string;
}
export interface RefreshRequest {
    /**
     * Token de rafraîchissement
     */
    'refreshToken': string;
}
export interface RoleRequestDTO {
    /**
     * Libellé du rôle (majuscules et underscores uniquement)
     */
    'libelle': string;
}
export interface RoleResponseDTO {
    /**
     * Identifiant unique du rôle
     */
    'id'?: number;
    /**
     * Libellé du rôle
     */
    'libelle'?: string;
    /**
     * Indique si le rôle est supprimé
     */
    'deleted'?: boolean;
}
export interface TokenResponse {
    /**
     * Token JWT d\'accès
     */
    'accessToken'?: string;
    /**
     * Token de rafraîchissement
     */
    'refreshToken'?: string;
    /**
     * Type de token
     */
    'tokenType'?: string;
    /**
     * Durée de validité du token en secondes
     */
    'expiresInSeconds'?: number;
}
export interface UtilisateurRequestDTO {
    /**
     * Nom de famille
     */
    'nom': string;
    /**
     * Prénom
     */
    'prenom': string;
    /**
     * Adresse email
     */
    'email': string;
    /**
     * Nom d\'utilisateur
     */
    'username': string;
    /**
     * Mot de passe
     */
    'motDePasse': string;
    /**
     * Numéro de téléphone (format Sénégal)
     */
    'telephone': string;
    /**
     * Rôle de l\'utilisateur
     */
    'role': string;
}
export interface UtilisateurResponseDTO {
    /**
     * Identifiant unique
     */
    'id'?: number;
    'nom'?: string;
    'prenom'?: string;
    'email'?: string;
    'telephone'?: string;
    'username'?: string;
    /**
     * Indique si le compte est actif
     */
    'actif'?: boolean;
    /**
     * Indique si le compte est supprimé
     */
    'deleted'?: boolean;
    /**
     * Rôle de l\'utilisateur
     */
    'role'?: string;
}

/**
 * AlumnisApi - axios parameter creator
 */
export const AlumnisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Permet de rechercher des alumni à l\'aide de filtres optionnels par entreprise et profession. 
         * @summary Recherche avancée des alumni
         * @param {string} [entreprise] Nom de l\&#39;entreprise actuelle de l\&#39;alumni
         * @param {string} [profession] Profession actuelle de l\&#39;alumni (ex: Data Scientist, Médecin...)
         * @param {string} [nom] Le nom de l\&#39;Alumni (ex: THIAM, DIOP...) 
         * @param {string} [prenom] Le prenom de l\&#39;Alumni (ex: Khoutbou, Ibrahima...) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAlumni: async (entreprise?: string, profession?: string, nom?: string, prenom?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/alumni/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (entreprise !== undefined) {
                localVarQueryParameter['entreprise'] = entreprise;
            }

            if (profession !== undefined) {
                localVarQueryParameter['profession'] = profession;
            }

            if (nom !== undefined) {
                localVarQueryParameter['nom'] = nom;
            }

            if (prenom !== undefined) {
                localVarQueryParameter['prenom'] = prenom;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AlumnisApi - functional programming interface
 */
export const AlumnisApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AlumnisApiAxiosParamCreator(configuration)
    return {
        /**
         * Permet de rechercher des alumni à l\'aide de filtres optionnels par entreprise et profession. 
         * @summary Recherche avancée des alumni
         * @param {string} [entreprise] Nom de l\&#39;entreprise actuelle de l\&#39;alumni
         * @param {string} [profession] Profession actuelle de l\&#39;alumni (ex: Data Scientist, Médecin...)
         * @param {string} [nom] Le nom de l\&#39;Alumni (ex: THIAM, DIOP...) 
         * @param {string} [prenom] Le prenom de l\&#39;Alumni (ex: Khoutbou, Ibrahima...) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchAlumni(entreprise?: string, profession?: string, nom?: string, prenom?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AlumniResponseDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchAlumni(entreprise, profession, nom, prenom, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AlumnisApi.searchAlumni']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AlumnisApi - factory interface
 */
export const AlumnisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AlumnisApiFp(configuration)
    return {
        /**
         * Permet de rechercher des alumni à l\'aide de filtres optionnels par entreprise et profession. 
         * @summary Recherche avancée des alumni
         * @param {string} [entreprise] Nom de l\&#39;entreprise actuelle de l\&#39;alumni
         * @param {string} [profession] Profession actuelle de l\&#39;alumni (ex: Data Scientist, Médecin...)
         * @param {string} [nom] Le nom de l\&#39;Alumni (ex: THIAM, DIOP...) 
         * @param {string} [prenom] Le prenom de l\&#39;Alumni (ex: Khoutbou, Ibrahima...) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAlumni(entreprise?: string, profession?: string, nom?: string, prenom?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AlumniResponseDTO>> {
            return localVarFp.searchAlumni(entreprise, profession, nom, prenom, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AlumnisApi - object-oriented interface
 */
export class AlumnisApi extends BaseAPI {
    /**
     * Permet de rechercher des alumni à l\'aide de filtres optionnels par entreprise et profession. 
     * @summary Recherche avancée des alumni
     * @param {string} [entreprise] Nom de l\&#39;entreprise actuelle de l\&#39;alumni
     * @param {string} [profession] Profession actuelle de l\&#39;alumni (ex: Data Scientist, Médecin...)
     * @param {string} [nom] Le nom de l\&#39;Alumni (ex: THIAM, DIOP...) 
     * @param {string} [prenom] Le prenom de l\&#39;Alumni (ex: Khoutbou, Ibrahima...) 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchAlumni(entreprise?: string, profession?: string, nom?: string, prenom?: string, options?: RawAxiosRequestConfig) {
        return AlumnisApiFp(this.configuration).searchAlumni(entreprise, profession, nom, prenom, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthentificationApi - axios parameter creator
 */
export const AuthentificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Crée un nouveau compte utilisateur
         * @summary Inscrire un nouvel Utilisateur
         * @param {UtilisateurRequestDTO} utilisateurRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inscrire: async (utilisateurRequestDTO: UtilisateurRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'utilisateurRequestDTO' is not null or undefined
            assertParamExists('inscrire', 'utilisateurRequestDTO', utilisateurRequestDTO)
            const localVarPath = `/auth/inscrire`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(utilisateurRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Authentifie un utilisateur et retourne un token JWT
         * @summary Connexion utilisateur
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/auth/connecter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Déconnecte l\'utilisateur et invalide le refresh token
         * @summary Déconnexion utilisateur
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (refreshRequest: RefreshRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshRequest' is not null or undefined
            assertParamExists('logout', 'refreshRequest', refreshRequest)
            const localVarPath = `/auth/deconnecter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permet de renouveler un token JWT expiré en utilisant le refresh token
         * @summary Rafraîchir le token JWT
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh: async (refreshRequest: RefreshRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshRequest' is not null or undefined
            assertParamExists('refresh', 'refreshRequest', refreshRequest)
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthentificationApi - functional programming interface
 */
export const AuthentificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthentificationApiAxiosParamCreator(configuration)
    return {
        /**
         * Crée un nouveau compte utilisateur
         * @summary Inscrire un nouvel Utilisateur
         * @param {UtilisateurRequestDTO} utilisateurRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inscrire(utilisateurRequestDTO: UtilisateurRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UtilisateurResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inscrire(utilisateurRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthentificationApi.inscrire']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Authentifie un utilisateur et retourne un token JWT
         * @summary Connexion utilisateur
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthentificationApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Déconnecte l\'utilisateur et invalide le refresh token
         * @summary Déconnexion utilisateur
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(refreshRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthentificationApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permet de renouveler un token JWT expiré en utilisant le refresh token
         * @summary Rafraîchir le token JWT
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refresh(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refresh(refreshRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthentificationApi.refresh']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthentificationApi - factory interface
 */
export const AuthentificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthentificationApiFp(configuration)
    return {
        /**
         * Crée un nouveau compte utilisateur
         * @summary Inscrire un nouvel Utilisateur
         * @param {UtilisateurRequestDTO} utilisateurRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inscrire(utilisateurRequestDTO: UtilisateurRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<UtilisateurResponseDTO> {
            return localVarFp.inscrire(utilisateurRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Authentifie un utilisateur et retourne un token JWT
         * @summary Connexion utilisateur
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Déconnecte l\'utilisateur et invalide le refresh token
         * @summary Déconnexion utilisateur
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(refreshRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Permet de renouveler un token JWT expiré en utilisant le refresh token
         * @summary Rafraîchir le token JWT
         * @param {RefreshRequest} refreshRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.refresh(refreshRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthentificationApi - object-oriented interface
 */
export class AuthentificationApi extends BaseAPI {
    /**
     * Crée un nouveau compte utilisateur
     * @summary Inscrire un nouvel Utilisateur
     * @param {UtilisateurRequestDTO} utilisateurRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public inscrire(utilisateurRequestDTO: UtilisateurRequestDTO, options?: RawAxiosRequestConfig) {
        return AuthentificationApiFp(this.configuration).inscrire(utilisateurRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Authentifie un utilisateur et retourne un token JWT
     * @summary Connexion utilisateur
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthentificationApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Déconnecte l\'utilisateur et invalide le refresh token
     * @summary Déconnexion utilisateur
     * @param {RefreshRequest} refreshRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig) {
        return AuthentificationApiFp(this.configuration).logout(refreshRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permet de renouveler un token JWT expiré en utilisant le refresh token
     * @summary Rafraîchir le token JWT
     * @param {RefreshRequest} refreshRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public refresh(refreshRequest: RefreshRequest, options?: RawAxiosRequestConfig) {
        return AuthentificationApiFp(this.configuration).refresh(refreshRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RlesApi - axios parameter creator
 */
export const RlesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Crée un nouveau rôle dans le système
         * @summary Créer un nouveau rôle
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRole: async (roleRequestDTO: RoleRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleRequestDTO' is not null or undefined
            assertParamExists('createRole', 'roleRequestDTO', roleRequestDTO)
            const localVarPath = `/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roleRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retourne la liste de tous les rôles disponibles dans le système
         * @summary Récupérer tous les rôles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRoles: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retourne les détails d\'un rôle spécifique
         * @summary Récupérer un rôle par son ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRoleById', 'id', id)
            const localVarPath = `/roles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Effectue une suppression logique (soft delete) d\'un rôle
         * @summary Supprimer logiquement un rôle
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        softDeleteRole: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('softDeleteRole', 'id', id)
            const localVarPath = `/roles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Met à jour les informations d\'un rôle
         * @summary Mettre à jour un rôle existant
         * @param {number} id 
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRole: async (id: number, roleRequestDTO: RoleRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRole', 'id', id)
            // verify required parameter 'roleRequestDTO' is not null or undefined
            assertParamExists('updateRole', 'roleRequestDTO', roleRequestDTO)
            const localVarPath = `/roles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roleRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RlesApi - functional programming interface
 */
export const RlesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RlesApiAxiosParamCreator(configuration)
    return {
        /**
         * Crée un nouveau rôle dans le système
         * @summary Créer un nouveau rôle
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRole(roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRole(roleRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RlesApi.createRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retourne la liste de tous les rôles disponibles dans le système
         * @summary Récupérer tous les rôles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllRoles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RoleResponseDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllRoles(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RlesApi.getAllRoles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retourne les détails d\'un rôle spécifique
         * @summary Récupérer un rôle par son ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoleById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoleById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RlesApi.getRoleById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Effectue une suppression logique (soft delete) d\'un rôle
         * @summary Supprimer logiquement un rôle
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softDeleteRole(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.softDeleteRole(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RlesApi.softDeleteRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Met à jour les informations d\'un rôle
         * @summary Mettre à jour un rôle existant
         * @param {number} id 
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRole(id: number, roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRole(id, roleRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RlesApi.updateRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RlesApi - factory interface
 */
export const RlesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RlesApiFp(configuration)
    return {
        /**
         * Crée un nouveau rôle dans le système
         * @summary Créer un nouveau rôle
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRole(roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<RoleResponseDTO> {
            return localVarFp.createRole(roleRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Retourne la liste de tous les rôles disponibles dans le système
         * @summary Récupérer tous les rôles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRoles(options?: RawAxiosRequestConfig): AxiosPromise<Array<RoleResponseDTO>> {
            return localVarFp.getAllRoles(options).then((request) => request(axios, basePath));
        },
        /**
         * Retourne les détails d\'un rôle spécifique
         * @summary Récupérer un rôle par son ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<RoleResponseDTO> {
            return localVarFp.getRoleById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Effectue une suppression logique (soft delete) d\'un rôle
         * @summary Supprimer logiquement un rôle
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        softDeleteRole(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.softDeleteRole(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Met à jour les informations d\'un rôle
         * @summary Mettre à jour un rôle existant
         * @param {number} id 
         * @param {RoleRequestDTO} roleRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRole(id: number, roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<RoleResponseDTO> {
            return localVarFp.updateRole(id, roleRequestDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RlesApi - object-oriented interface
 */
export class RlesApi extends BaseAPI {
    /**
     * Crée un nouveau rôle dans le système
     * @summary Créer un nouveau rôle
     * @param {RoleRequestDTO} roleRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createRole(roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig) {
        return RlesApiFp(this.configuration).createRole(roleRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retourne la liste de tous les rôles disponibles dans le système
     * @summary Récupérer tous les rôles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllRoles(options?: RawAxiosRequestConfig) {
        return RlesApiFp(this.configuration).getAllRoles(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retourne les détails d\'un rôle spécifique
     * @summary Récupérer un rôle par son ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoleById(id: number, options?: RawAxiosRequestConfig) {
        return RlesApiFp(this.configuration).getRoleById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Effectue une suppression logique (soft delete) d\'un rôle
     * @summary Supprimer logiquement un rôle
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public softDeleteRole(id: number, options?: RawAxiosRequestConfig) {
        return RlesApiFp(this.configuration).softDeleteRole(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Met à jour les informations d\'un rôle
     * @summary Mettre à jour un rôle existant
     * @param {number} id 
     * @param {RoleRequestDTO} roleRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRole(id: number, roleRequestDTO: RoleRequestDTO, options?: RawAxiosRequestConfig) {
        return RlesApiFp(this.configuration).updateRole(id, roleRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UtilisateursApi - axios parameter creator
 */
export const UtilisateursApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ALUMNI de compléter son profil avec les informations spécifiques : profession et entreprise. 
         * @summary Compléter son profil alumni
         * @param {AlumniProfilRequestDTO} alumniProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completerProfilAlumni: async (alumniProfilRequestDTO: AlumniProfilRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'alumniProfilRequestDTO' is not null or undefined
            assertParamExists('completerProfilAlumni', 'alumniProfilRequestDTO', alumniProfilRequestDTO)
            const localVarPath = `/utilisateurs/completer-profil/alumni`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(alumniProfilRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ETUDIANT de compléter son profil avec les informations spécifiques : numeroCarteEtudiant, filiere et niveau. 
         * @summary Compléter son profil étudiant
         * @param {EtudiantProfilRequestDTO} etudiantProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completerProfilEtudiant: async (etudiantProfilRequestDTO: EtudiantProfilRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'etudiantProfilRequestDTO' is not null or undefined
            assertParamExists('completerProfilEtudiant', 'etudiantProfilRequestDTO', etudiantProfilRequestDTO)
            const localVarPath = `/utilisateurs/completer-profil/etudiant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(etudiantProfilRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Vérifie si un email est déjà utilisé dans le système
         * @summary Vérifier si un email existe
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailExists: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('emailExists', 'email', email)
            const localVarPath = `/utilisateurs/exists/email/{email}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permet de lister les utilisateurs avec pagination, filtre par actif et filtre par suppression (soft delete). 
         * @summary Lister et filtrer les utilisateurs
         * @param {boolean} [actif] Filtre sur l\&#39;état d\&#39;activation du compte
         * @param {boolean} [deleted] Filtre sur l\&#39;état de suppression logique (soft delete)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [sort] Format: champ,ordre (asc|desc)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUtilisateursFiltered: async (actif?: boolean, deleted?: boolean, page?: number, size?: number, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/utilisateurs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (actif !== undefined) {
                localVarQueryParameter['actif'] = actif;
            }

            if (deleted !== undefined) {
                localVarQueryParameter['deleted'] = deleted;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retourne les informations d\'un utilisateur par son email
         * @summary Récupérer un utilisateur par email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUtilisateurByEmail: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('getUtilisateurByEmail', 'email', email)
            const localVarPath = `/utilisateurs/email/{email}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Vérifie si un username est déjà utilisé dans le système
         * @summary Vérifier si un username existe
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usernameExists: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('usernameExists', 'username', username)
            const localVarPath = `/utilisateurs/exists/username/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UtilisateursApi - functional programming interface
 */
export const UtilisateursApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UtilisateursApiAxiosParamCreator(configuration)
    return {
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ALUMNI de compléter son profil avec les informations spécifiques : profession et entreprise. 
         * @summary Compléter son profil alumni
         * @param {AlumniProfilRequestDTO} alumniProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completerProfilAlumni(alumniProfilRequestDTO: AlumniProfilRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AlumniResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completerProfilAlumni(alumniProfilRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.completerProfilAlumni']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ETUDIANT de compléter son profil avec les informations spécifiques : numeroCarteEtudiant, filiere et niveau. 
         * @summary Compléter son profil étudiant
         * @param {EtudiantProfilRequestDTO} etudiantProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completerProfilEtudiant(etudiantProfilRequestDTO: EtudiantProfilRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EtudiantResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completerProfilEtudiant(etudiantProfilRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.completerProfilEtudiant']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Vérifie si un email est déjà utilisé dans le système
         * @summary Vérifier si un email existe
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailExists(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailExists(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.emailExists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permet de lister les utilisateurs avec pagination, filtre par actif et filtre par suppression (soft delete). 
         * @summary Lister et filtrer les utilisateurs
         * @param {boolean} [actif] Filtre sur l\&#39;état d\&#39;activation du compte
         * @param {boolean} [deleted] Filtre sur l\&#39;état de suppression logique (soft delete)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [sort] Format: champ,ordre (asc|desc)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUtilisateursFiltered(actif?: boolean, deleted?: boolean, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllUtilisateursFiltered200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUtilisateursFiltered(actif, deleted, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.getAllUtilisateursFiltered']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retourne les informations d\'un utilisateur par son email
         * @summary Récupérer un utilisateur par email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUtilisateurByEmail(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UtilisateurResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUtilisateurByEmail(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.getUtilisateurByEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Vérifie si un username est déjà utilisé dans le système
         * @summary Vérifier si un username existe
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usernameExists(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usernameExists(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilisateursApi.usernameExists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UtilisateursApi - factory interface
 */
export const UtilisateursApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UtilisateursApiFp(configuration)
    return {
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ALUMNI de compléter son profil avec les informations spécifiques : profession et entreprise. 
         * @summary Compléter son profil alumni
         * @param {AlumniProfilRequestDTO} alumniProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completerProfilAlumni(alumniProfilRequestDTO: AlumniProfilRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<AlumniResponseDTO> {
            return localVarFp.completerProfilAlumni(alumniProfilRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Permet à l\'utilisateur connecté ayant le rôle ETUDIANT de compléter son profil avec les informations spécifiques : numeroCarteEtudiant, filiere et niveau. 
         * @summary Compléter son profil étudiant
         * @param {EtudiantProfilRequestDTO} etudiantProfilRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completerProfilEtudiant(etudiantProfilRequestDTO: EtudiantProfilRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<EtudiantResponseDTO> {
            return localVarFp.completerProfilEtudiant(etudiantProfilRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Vérifie si un email est déjà utilisé dans le système
         * @summary Vérifier si un email existe
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailExists(email: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.emailExists(email, options).then((request) => request(axios, basePath));
        },
        /**
         * Permet de lister les utilisateurs avec pagination, filtre par actif et filtre par suppression (soft delete). 
         * @summary Lister et filtrer les utilisateurs
         * @param {boolean} [actif] Filtre sur l\&#39;état d\&#39;activation du compte
         * @param {boolean} [deleted] Filtre sur l\&#39;état de suppression logique (soft delete)
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [sort] Format: champ,ordre (asc|desc)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUtilisateursFiltered(actif?: boolean, deleted?: boolean, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllUtilisateursFiltered200Response> {
            return localVarFp.getAllUtilisateursFiltered(actif, deleted, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Retourne les informations d\'un utilisateur par son email
         * @summary Récupérer un utilisateur par email
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUtilisateurByEmail(email: string, options?: RawAxiosRequestConfig): AxiosPromise<UtilisateurResponseDTO> {
            return localVarFp.getUtilisateurByEmail(email, options).then((request) => request(axios, basePath));
        },
        /**
         * Vérifie si un username est déjà utilisé dans le système
         * @summary Vérifier si un username existe
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usernameExists(username: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.usernameExists(username, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UtilisateursApi - object-oriented interface
 */
export class UtilisateursApi extends BaseAPI {
    /**
     * Permet à l\'utilisateur connecté ayant le rôle ALUMNI de compléter son profil avec les informations spécifiques : profession et entreprise. 
     * @summary Compléter son profil alumni
     * @param {AlumniProfilRequestDTO} alumniProfilRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public completerProfilAlumni(alumniProfilRequestDTO: AlumniProfilRequestDTO, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).completerProfilAlumni(alumniProfilRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permet à l\'utilisateur connecté ayant le rôle ETUDIANT de compléter son profil avec les informations spécifiques : numeroCarteEtudiant, filiere et niveau. 
     * @summary Compléter son profil étudiant
     * @param {EtudiantProfilRequestDTO} etudiantProfilRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public completerProfilEtudiant(etudiantProfilRequestDTO: EtudiantProfilRequestDTO, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).completerProfilEtudiant(etudiantProfilRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Vérifie si un email est déjà utilisé dans le système
     * @summary Vérifier si un email existe
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public emailExists(email: string, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).emailExists(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permet de lister les utilisateurs avec pagination, filtre par actif et filtre par suppression (soft delete). 
     * @summary Lister et filtrer les utilisateurs
     * @param {boolean} [actif] Filtre sur l\&#39;état d\&#39;activation du compte
     * @param {boolean} [deleted] Filtre sur l\&#39;état de suppression logique (soft delete)
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [sort] Format: champ,ordre (asc|desc)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllUtilisateursFiltered(actif?: boolean, deleted?: boolean, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).getAllUtilisateursFiltered(actif, deleted, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retourne les informations d\'un utilisateur par son email
     * @summary Récupérer un utilisateur par email
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUtilisateurByEmail(email: string, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).getUtilisateurByEmail(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Vérifie si un username est déjà utilisé dans le système
     * @summary Vérifier si un username existe
     * @param {string} username 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usernameExists(username: string, options?: RawAxiosRequestConfig) {
        return UtilisateursApiFp(this.configuration).usernameExists(username, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ValidationApi - axios parameter creator
 */
export const ValidationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Génère et envoie un code de validation par email
         * @summary Envoyer un code de validation
         * @param {CodeValidationRequestDTO} codeValidationRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        envoyerCode: async (codeValidationRequestDTO: CodeValidationRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'codeValidationRequestDTO' is not null or undefined
            assertParamExists('envoyerCode', 'codeValidationRequestDTO', codeValidationRequestDTO)
            const localVarPath = `/validation/envoyer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(codeValidationRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Valide un code fourni par l\'utilisateur
         * @summary Vérifier un code de validation
         * @param {CodeValidationCheckDTO} codeValidationCheckDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifierCode: async (codeValidationCheckDTO: CodeValidationCheckDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'codeValidationCheckDTO' is not null or undefined
            assertParamExists('verifierCode', 'codeValidationCheckDTO', codeValidationCheckDTO)
            const localVarPath = `/validation/verifier`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(codeValidationCheckDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ValidationApi - functional programming interface
 */
export const ValidationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ValidationApiAxiosParamCreator(configuration)
    return {
        /**
         * Génère et envoie un code de validation par email
         * @summary Envoyer un code de validation
         * @param {CodeValidationRequestDTO} codeValidationRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async envoyerCode(codeValidationRequestDTO: CodeValidationRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.envoyerCode(codeValidationRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ValidationApi.envoyerCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Valide un code fourni par l\'utilisateur
         * @summary Vérifier un code de validation
         * @param {CodeValidationCheckDTO} codeValidationCheckDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifierCode(codeValidationCheckDTO: CodeValidationCheckDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifierCode(codeValidationCheckDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ValidationApi.verifierCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ValidationApi - factory interface
 */
export const ValidationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ValidationApiFp(configuration)
    return {
        /**
         * Génère et envoie un code de validation par email
         * @summary Envoyer un code de validation
         * @param {CodeValidationRequestDTO} codeValidationRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        envoyerCode(codeValidationRequestDTO: CodeValidationRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.envoyerCode(codeValidationRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Valide un code fourni par l\'utilisateur
         * @summary Vérifier un code de validation
         * @param {CodeValidationCheckDTO} codeValidationCheckDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifierCode(codeValidationCheckDTO: CodeValidationCheckDTO, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.verifierCode(codeValidationCheckDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ValidationApi - object-oriented interface
 */
export class ValidationApi extends BaseAPI {
    /**
     * Génère et envoie un code de validation par email
     * @summary Envoyer un code de validation
     * @param {CodeValidationRequestDTO} codeValidationRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public envoyerCode(codeValidationRequestDTO: CodeValidationRequestDTO, options?: RawAxiosRequestConfig) {
        return ValidationApiFp(this.configuration).envoyerCode(codeValidationRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Valide un code fourni par l\'utilisateur
     * @summary Vérifier un code de validation
     * @param {CodeValidationCheckDTO} codeValidationCheckDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifierCode(codeValidationCheckDTO: CodeValidationCheckDTO, options?: RawAxiosRequestConfig) {
        return ValidationApiFp(this.configuration).verifierCode(codeValidationCheckDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



