/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MsUserApiDeGestionDesUtilisateurs);
  }
}(this, function(expect, MsUserApiDeGestionDesUtilisateurs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EtudiantResponseDTO', function() {
    it('should create an instance of EtudiantResponseDTO', function() {
      // uncomment below and update the code to test EtudiantResponseDTO
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be.a(MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property nom (base name: "nom")', function() {
      // uncomment below and update the code to test the property nom
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property prenom (base name: "prenom")', function() {
      // uncomment below and update the code to test the property prenom
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property telephone (base name: "telephone")', function() {
      // uncomment below and update the code to test the property telephone
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property numeroCarteEtudiant (base name: "numeroCarteEtudiant")', function() {
      // uncomment below and update the code to test the property numeroCarteEtudiant
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property niveau (base name: "niveau")', function() {
      // uncomment below and update the code to test the property niveau
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property filiere (base name: "filiere")', function() {
      // uncomment below and update the code to test the property filiere
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property actif (base name: "actif")', function() {
      // uncomment below and update the code to test the property actif
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property deleted (base name: "deleted")', function() {
      // uncomment below and update the code to test the property deleted
      //var instance = new MsUserApiDeGestionDesUtilisateurs.EtudiantResponseDTO();
      //expect(instance).to.be();
    });

  });

}));
