/**
 * MS User - API de Gestion des Utilisateurs
 * Microservice de gestion des utilisateurs et authentification pour la plateforme UASZ Alumni. Cette API permet de gérer les utilisateurs, les rôles, les permissions et l'authentification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MsUserApiDeGestionDesUtilisateurs);
  }
}(this, function(expect, MsUserApiDeGestionDesUtilisateurs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MsUserApiDeGestionDesUtilisateurs.RoleRequestDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RoleRequestDTO', function() {
    it('should create an instance of RoleRequestDTO', function() {
      // uncomment below and update the code to test RoleRequestDTO
      //var instance = new MsUserApiDeGestionDesUtilisateurs.RoleRequestDTO();
      //expect(instance).to.be.a(MsUserApiDeGestionDesUtilisateurs.RoleRequestDTO);
    });

    it('should have the property libelle (base name: "libelle")', function() {
      // uncomment below and update the code to test the property libelle
      //var instance = new MsUserApiDeGestionDesUtilisateurs.RoleRequestDTO();
      //expect(instance).to.be();
    });

  });

}));
